#handler --> X
helpers --> pep.py(all), lets(X), lets(exceptions class 중복 3개 있음)
loginEvent.py/loginFailedException_pep로 고쳐놓음
objects --> pep.py(all), lets(glob)
pubSubHandlers --> pep.py(X), lets(X)